exp_root_dir: /home/wyy/exp/pose_transfer
exp_name: test_encoder

pretrained_model_path: /home/nfs/wyy/models/sd-image-variations-diffusers
data_root_dir: /home/nfs/wyy/data/deepfashion/Data
seed: 42

load_state: False
load_state_exp_name: test_ca
load_state_epoch: 339

learning_rate: 0.0001
decay: 0.001

save_state_epoch: 10
num_epochs: 500
batch_size: 10
eval_batch_size: 10
eval_step: 3000
eval_scheduler: ddim
eval_image_num: 4

# how to inject pose control?
# 1. ContolNet 2. Concatenate (both after vae encoder) 3. Addition(After conv_in in unet)
pose_injection: addition_after_conv_in # concat_before_conv_in, addition_after_conv_in

image_encoder: dinov2
refer_sdvae: True
unet_trainable_module: cross_attn # transformer, cross_attn, self_cross_attn, all
ref_encoder_type: dinov2 # clip_all, clip_global, dinov2, clip_multi
use_clip_proj: False
cfg_zero_image_first: False
dinov2_path: /home/nfs/wyy/models/dinov2
dinov2_version: dinov2_vitg14

num_inf_images_per_prompt: 1
num_inference_steps: 50
scale_factor: 0.18215
guidance_scale: 2.5
cfg_eta: 0.1
controlnet_conditioning_scale: 1.0

device: cuda
mixed_precision: 'bf16' #'no','fp16','bf16 or 'fp8'
enable_xformers_memory_efficient_attention: True
gradient_checkpointing: True
gradient_accumulate_steps: 2
num_workers: 32